/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OverlayTokenRouteImport } from './routes/overlay.$token'
import { Route as JoinInviteCodeRouteImport } from './routes/join.$inviteCode'
import { Route as AppVenueRouteImport } from './routes/_app.venue'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppCreateRouteImport } from './routes/_app.create'
import { Route as AppAdminRouteImport } from './routes/_app.admin'
import { Route as AppGameGameIdResultsRouteImport } from './routes/_app.game.$gameId.results'
import { Route as AppGameGameIdOverlayRouteImport } from './routes/_app.game.$gameId.overlay'
import { Route as AppGameGameIdLobbyRouteImport } from './routes/_app.game.$gameId.lobby'
import { Route as AppGameGameIdLiveRouteImport } from './routes/_app.game.$gameId.live'
import { Route as AppGameGameIdInviteRouteImport } from './routes/_app.game.$gameId.invite'

const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OverlayTokenRoute = OverlayTokenRouteImport.update({
  id: '/overlay/$token',
  path: '/overlay/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinInviteCodeRoute = JoinInviteCodeRouteImport.update({
  id: '/join/$inviteCode',
  path: '/join/$inviteCode',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVenueRoute = AppVenueRouteImport.update({
  id: '/venue',
  path: '/venue',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCreateRoute = AppCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppGameGameIdResultsRoute = AppGameGameIdResultsRouteImport.update({
  id: '/game/$gameId/results',
  path: '/game/$gameId/results',
  getParentRoute: () => AppRoute,
} as any)
const AppGameGameIdOverlayRoute = AppGameGameIdOverlayRouteImport.update({
  id: '/game/$gameId/overlay',
  path: '/game/$gameId/overlay',
  getParentRoute: () => AppRoute,
} as any)
const AppGameGameIdLobbyRoute = AppGameGameIdLobbyRouteImport.update({
  id: '/game/$gameId/lobby',
  path: '/game/$gameId/lobby',
  getParentRoute: () => AppRoute,
} as any)
const AppGameGameIdLiveRoute = AppGameGameIdLiveRouteImport.update({
  id: '/game/$gameId/live',
  path: '/game/$gameId/live',
  getParentRoute: () => AppRoute,
} as any)
const AppGameGameIdInviteRoute = AppGameGameIdInviteRouteImport.update({
  id: '/game/$gameId/invite',
  path: '/game/$gameId/invite',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/docs': typeof DocsRoute
  '/admin': typeof AppAdminRoute
  '/create': typeof AppCreateRoute
  '/dashboard': typeof AppDashboardRoute
  '/profile': typeof AppProfileRoute
  '/venue': typeof AppVenueRoute
  '/join/$inviteCode': typeof JoinInviteCodeRoute
  '/overlay/$token': typeof OverlayTokenRoute
  '/game/$gameId/invite': typeof AppGameGameIdInviteRoute
  '/game/$gameId/live': typeof AppGameGameIdLiveRoute
  '/game/$gameId/lobby': typeof AppGameGameIdLobbyRoute
  '/game/$gameId/overlay': typeof AppGameGameIdOverlayRoute
  '/game/$gameId/results': typeof AppGameGameIdResultsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/docs': typeof DocsRoute
  '/admin': typeof AppAdminRoute
  '/create': typeof AppCreateRoute
  '/dashboard': typeof AppDashboardRoute
  '/profile': typeof AppProfileRoute
  '/venue': typeof AppVenueRoute
  '/join/$inviteCode': typeof JoinInviteCodeRoute
  '/overlay/$token': typeof OverlayTokenRoute
  '/game/$gameId/invite': typeof AppGameGameIdInviteRoute
  '/game/$gameId/live': typeof AppGameGameIdLiveRoute
  '/game/$gameId/lobby': typeof AppGameGameIdLobbyRoute
  '/game/$gameId/overlay': typeof AppGameGameIdOverlayRoute
  '/game/$gameId/results': typeof AppGameGameIdResultsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/docs': typeof DocsRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/create': typeof AppCreateRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/venue': typeof AppVenueRoute
  '/join/$inviteCode': typeof JoinInviteCodeRoute
  '/overlay/$token': typeof OverlayTokenRoute
  '/_app/game/$gameId/invite': typeof AppGameGameIdInviteRoute
  '/_app/game/$gameId/live': typeof AppGameGameIdLiveRoute
  '/_app/game/$gameId/lobby': typeof AppGameGameIdLobbyRoute
  '/_app/game/$gameId/overlay': typeof AppGameGameIdOverlayRoute
  '/_app/game/$gameId/results': typeof AppGameGameIdResultsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/docs'
    | '/admin'
    | '/create'
    | '/dashboard'
    | '/profile'
    | '/venue'
    | '/join/$inviteCode'
    | '/overlay/$token'
    | '/game/$gameId/invite'
    | '/game/$gameId/live'
    | '/game/$gameId/lobby'
    | '/game/$gameId/overlay'
    | '/game/$gameId/results'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/docs'
    | '/admin'
    | '/create'
    | '/dashboard'
    | '/profile'
    | '/venue'
    | '/join/$inviteCode'
    | '/overlay/$token'
    | '/game/$gameId/invite'
    | '/game/$gameId/live'
    | '/game/$gameId/lobby'
    | '/game/$gameId/overlay'
    | '/game/$gameId/results'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/docs'
    | '/_app/admin'
    | '/_app/create'
    | '/_app/dashboard'
    | '/_app/profile'
    | '/_app/venue'
    | '/join/$inviteCode'
    | '/overlay/$token'
    | '/_app/game/$gameId/invite'
    | '/_app/game/$gameId/live'
    | '/_app/game/$gameId/lobby'
    | '/_app/game/$gameId/overlay'
    | '/_app/game/$gameId/results'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  DocsRoute: typeof DocsRoute
  JoinInviteCodeRoute: typeof JoinInviteCodeRoute
  OverlayTokenRoute: typeof OverlayTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overlay/$token': {
      id: '/overlay/$token'
      path: '/overlay/$token'
      fullPath: '/overlay/$token'
      preLoaderRoute: typeof OverlayTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$inviteCode': {
      id: '/join/$inviteCode'
      path: '/join/$inviteCode'
      fullPath: '/join/$inviteCode'
      preLoaderRoute: typeof JoinInviteCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/venue': {
      id: '/_app/venue'
      path: '/venue'
      fullPath: '/venue'
      preLoaderRoute: typeof AppVenueRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/create': {
      id: '/_app/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof AppCreateRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/game/$gameId/results': {
      id: '/_app/game/$gameId/results'
      path: '/game/$gameId/results'
      fullPath: '/game/$gameId/results'
      preLoaderRoute: typeof AppGameGameIdResultsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/game/$gameId/overlay': {
      id: '/_app/game/$gameId/overlay'
      path: '/game/$gameId/overlay'
      fullPath: '/game/$gameId/overlay'
      preLoaderRoute: typeof AppGameGameIdOverlayRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/game/$gameId/lobby': {
      id: '/_app/game/$gameId/lobby'
      path: '/game/$gameId/lobby'
      fullPath: '/game/$gameId/lobby'
      preLoaderRoute: typeof AppGameGameIdLobbyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/game/$gameId/live': {
      id: '/_app/game/$gameId/live'
      path: '/game/$gameId/live'
      fullPath: '/game/$gameId/live'
      preLoaderRoute: typeof AppGameGameIdLiveRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/game/$gameId/invite': {
      id: '/_app/game/$gameId/invite'
      path: '/game/$gameId/invite'
      fullPath: '/game/$gameId/invite'
      preLoaderRoute: typeof AppGameGameIdInviteRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppCreateRoute: typeof AppCreateRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppProfileRoute: typeof AppProfileRoute
  AppVenueRoute: typeof AppVenueRoute
  AppGameGameIdInviteRoute: typeof AppGameGameIdInviteRoute
  AppGameGameIdLiveRoute: typeof AppGameGameIdLiveRoute
  AppGameGameIdLobbyRoute: typeof AppGameGameIdLobbyRoute
  AppGameGameIdOverlayRoute: typeof AppGameGameIdOverlayRoute
  AppGameGameIdResultsRoute: typeof AppGameGameIdResultsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppCreateRoute: AppCreateRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppProfileRoute: AppProfileRoute,
  AppVenueRoute: AppVenueRoute,
  AppGameGameIdInviteRoute: AppGameGameIdInviteRoute,
  AppGameGameIdLiveRoute: AppGameGameIdLiveRoute,
  AppGameGameIdLobbyRoute: AppGameGameIdLobbyRoute,
  AppGameGameIdOverlayRoute: AppGameGameIdOverlayRoute,
  AppGameGameIdResultsRoute: AppGameGameIdResultsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  DocsRoute: DocsRoute,
  JoinInviteCodeRoute: JoinInviteCodeRoute,
  OverlayTokenRoute: OverlayTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
